#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo
  echo "  Usage:   leader PORT COMMAND"
  echo "  Example: leader 8080 nginx"
  echo
  exit 1
fi

if [[ `lsof -i :$1 -sTCP:LISTEN` ]]; then
  echo "Leader detected port $1 already in use. Ignoring."
  while :; do sleep 1; done
else
  shift
  echo $@
  exec "$@"
fi
